preserve_hierarchy: 1
files:
  - source: /src/locales/en.json
    translation: /src/locales/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        zh-CN: zh_cn
        zh-TW: zh_tw
        zh-HK: zh_hk
        cs-CZ: cs_cz
